name: Build and push

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

env:
  # renovate: datasource=repology depName=homebrew/postgresql@18 versioning=loose
  LATEST_POSTGRES_VERSION: "18.4"
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  DOCKERHUB_IMAGE: docker.io/${{ github.repository }}

permissions: {}

jobs:
  base-images:
    # for security reason, we only build these images in our repository and on the main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        flavor:
          - alpine
          - trixie
        pg_version:
          - "13"
          - "14"
          - "15"
          - "16"
          - "17"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          file: "Dockerfile.${{ matrix.flavor }}"
          push: true
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x
          build-args: |
            "PGTARGET=${{ env.LATEST_POSTGRES_VERSION }}"
          target: "build-${{ matrix.pg_version }}"
          tags: "${{ env.GHCR_IMAGE }}:build-${{ matrix.pg_version }}-${{ matrix.flavor }}"
          cache-to: type=inline
          cache-from: type=registry,ref=${{ env.GHCR_IMAGE }}:build-${{ matrix.pg_version }}-${{ matrix.flavor }}

  target-images:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    needs: base-images
    # otherwise, it would skip the build entirely (because the base step does not run)
    if: always()
    env:
      # but still use our public caches in any case
      # they might be outdated, in which case a full rebuild will be triggered
      CACHE_FROM: |
        type=registry,ref=ghcr.io/${{ github.repository }}:build-13-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:build-14-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:build-15-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:build-16-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:build-17-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.pg_target.PG_VERSION }}-${{ matrix.operating_system.flavor }}
        type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.pg_target.PG_VERSION }}-${{ matrix.operating_system.flavor }}${{ matrix.operating_system.OS_VERSION }}
        type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.pg_target.PG_VERSION }}-${{ matrix.operating_system.alias }}

    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        operating_system:
          - flavor: "alpine"
            # renovate: datasource=docker depName=alpine versioning=docker
            OS_VERSION: "3.23"
            alias: "alpine"
          - flavor: "trixie"
            alias: "debian"
        pg_target:
          - # renovate: datasource=repology depName=homebrew/postgresql@14 versioning=loose
            PG_VERSION: "14.23"
          - # renovate: datasource=repology depName=homebrew/postgresql@15 versioning=loose
            PG_VERSION: "15.18"
          - # renovate: datasource=repology depName=homebrew/postgresql@16 versioning=loose
            PG_VERSION: "16.14"
          - # renovate: datasource=repology depName=homebrew/postgresql@17 versioning=loose
            PG_VERSION: "17.10"
          - # renovate: datasource=repology depName=homebrew/postgresql@18 versioning=loose
            PG_VERSION: "18.4"

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ env.GHCR_IMAGE }}
            ${{ env.DOCKERHUB_IMAGE }}
          flavor: |
            latest=false
          # add a .0 to each Postgres version so it is compliant with semantic version
          # note that the .0 never ends up on an actual tag
          tags: |
            type=semver,pattern={{major}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.flavor }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.flavor }}
            type=semver,pattern={{major}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.flavor }}${{ matrix.operating_system.OS_VERSION }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.flavor }}${{ matrix.operating_system.OS_VERSION }}
            type=semver,pattern={{major}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.alias }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.pg_target.PG_VERSION }}.0,suffix=-${{ matrix.operating_system.alias }}

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Push image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          file: "Dockerfile.${{ matrix.operating_system.flavor }}"
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "PGTARGET=${{ matrix.pg_target.PG_VERSION }}"
          push: true
          cache-to: type=inline
          cache-from: "${{ env.CACHE_FROM }}"

      - name: Push latest image for each supported OS
        if: github.ref == 'refs/heads/main' && matrix.pg_target.PG_VERSION == env.LATEST_POSTGRES_VERSION
        uses: docker/build-push-action@v6
        with:
          file: "Dockerfile.${{ matrix.operating_system.flavor }}"
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x
          tags: |
            "${{ env.GHCR_IMAGE }}:${{ matrix.operating_system.flavor }}"
            "${{ env.GHCR_IMAGE }}:${{ matrix.operating_system.alias }}"
            "${{ env.DOCKERHUB_IMAGE }}:${{ matrix.operating_system.flavor }}"
            "${{ env.DOCKERHUB_IMAGE }}:${{ matrix.operating_system.alias }}"
          build-args: |
            "PGTARGET=${{ matrix.pg_target.PG_VERSION }}"
          push: true
          cache-to: type=inline
          cache-from: "${{ env.CACHE_FROM }}"

      - name: Push general latest image
        if: github.ref == 'refs/heads/main' && matrix.pg_target.PG_VERSION == env.LATEST_POSTGRES_VERSION && matrix.operating_system.flavor == 'alpine'
        uses: docker/build-push-action@v6
        with:
          file: "Dockerfile.${{ matrix.operating_system.flavor }}"
          platforms: linux/amd64,linux/arm64,linux/riscv64,linux/ppc64le,linux/s390x
          tags: |
            "${{ env.GHCR_IMAGE }}:latest"
            "${{ env.DOCKERHUB_IMAGE }}:latest"
          build-args: |
            "PGTARGET=${{ matrix.pg_target.PG_VERSION }}"
          push: true
          cache-to: type=inline
          cache-from: "${{ env.CACHE_FROM }}"
